import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Layout } from '@/components/layout';
import { GraphqlProvider } from '@/components/graphql/GraphqlProvider';

const fontSans = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <GraphqlProvider uri={process.env.GRAPHQL_URL as string}>
        <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
          <Layout>{children}</Layout>
        </body>
      </GraphqlProvider>
    </html>
  );
}
